name: g1-vision-mujoco
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pyyaml
  - pip:
      - mujoco==3.2.7
      - onnxruntime==1.20.1
      - opencv-python==4.10.0.84

